services:
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    container_name: api_server
    restart: always
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - shared_storage:/app/data   #shared volume bridge
    networks:
      - app-network
    depends_on:
      mongo_db:
        condition: service_healthy
      rabbit_mq:
        condition: service_healthy

  background-worker:
    build:
      context: ./background-worker
      dockerfile: Dockerfile
    container_name: background_worker
    restart: always
    env_file:
      - ./.env 
    environment:
      - DERIVATIVES_DIR=/app/data/derivatives
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit_mq:5672
    volumes:
      - shared_storage:/app/data # mounts identical volume as api-server
    networks:
      - app-network
    depends_on:
       rabbit_mq:
          condition: service_healthy # won't pull tasks until RabbitMQ is completely green

  mongo_db:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    command: --replSet rs0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongo_init:
    image: mongo:6.0
    depends_on:
      mongo_db:
        condition: service_healthy
    networks:
      - app-network
    restart: "no"
    entrypoint: >
      mongosh --host mongo_db:27017 --eval
      'rs.initiate({_id:"rs0",members:[{_id:0,host:"mongo_db:27017"}]})'
  
  rabbit_mq:
    image: rabbitmq:3-management-alpine
    container_name: rabbit_mq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
  shared_storage: 